### ISSUE TITLE
Non consistent way of pressing map button

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#183] opened 2015-07-06 15:46 UTC
A little pre-story: Recently Quake Live has got a new update with a new map Elder. I was impressed how buttons work there - you don't need to fire directly on the button to press it, but it can be opened by the spalsh of RL/GL/PG. That feature opens quite fast and different ways of pressing buttons. https://youtu.be/3rqCas030JY

After that I decided to test similar ways in WSW, cause I was sure that buttons can be pressed only by direct shots there. That's what I've got after the test: http://youtu.be/nDt9SmwyxhE

So as you can see:
- usually our buttons can be pressed only by a direct shots
- but there is a strange case where button can be pressed by a splash damage of a rotated wall
- also EB shot doesn't work (Rail shot works in QL actually)

**Comment by viciious** [comment] 2015-07-09 19:43
Fixed in f7e6ca5b526ee348c5b55ed25ae61751e81e04ad and 5cdc909dccce2d36409f208b413ba72c24d12915

**Comment by adem4ik** [comment] 2015-07-10 18:27
all the previous issues are fixed now, but i've found a bit more:
- you can't open door by a shot right after its closing, there is a delay like 1-2 seconds between a moment when door gets closed and a moment when a button starts to work for shots.
- second issue seems like a result of the previous one, but i would like to point it too. if you stand near the button it gets pressed constantly, so the door won't be closed until you'll go away from the button. but if you shot the button constantly (from LG, PG, MG) it will be closed no matter what, then it will wait for 1-2 seconds and will be opened again. i think constant shots should give the same result as standing near the button.

Video: https://youtu.be/p4_bnKGh9_o

**Comment by viciious** [comment] 2015-07-10 18:37
Not a bug. the door has a cooldown timer.

**Closed as completed by viciious** 2015-07-10 18:37 UTC
Labels: bug, enhancement
