### ISSUE TITLE
Multiple negative values of Demojump breake manual POV switch

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#278] opened 2015-11-11 08:57 UTC
Warsow 2.0, steps to reproduce:

1) Download this demo https://yadi.sk/d/OVWVqWXzkNmrU and drop into /basewsw/demos
2) Start the Warsow and open the demo
3) Jump to somewhere in the middle of the demo
4) Use "demojump -10" & try to switch the POV manually (POV should be changed)
6) Use "demojump -10" & try to switch the POV once more

Result: POV doesn't want to switch for 10 seconds.

Happens as on Windows 10 as on Kubuntu 15.10. Similar bug have been reported multiple times and it was somehow fixed in 1.0, but it came back in 1.5:
https://www.warsow.gg/forum/thread/t/215280
https://www.warsow.gg/forum/thread/16148/1

**Comment by viciious** [comment] 2015-12-12 11:07
Can't reproduce anymore.

**Comment by adem4ik** [comment] 2015-12-16 05:09
I have updated steps to reproduce, bug won't happen after 1st "demojump -10", only after 2nd and the following tries.

**Comment by viciious** [comment] 2015-12-17 19:13
Fixed in 2e6d1895baf5ede9bce3ea386e5b4727e9d5aaa6.

**Closed as completed by viciious** 2015-12-17 19:13 UTC

**Comment by adem4ik** [comment] 2015-12-17 20:11
I do confirm, works like a magic now.

BIG THANKS!
