### ISSUE TITLE
No walljump sound while performing WJ on the ground

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#306] opened 2016-03-07 11:15 UTC
The minimum walljump height was disabled in this PR #295, so you can perform WJ by pressing Dash and Move Up staying next to the wall. But now there is no WJ sound for this trick, it plays dash sound instead:
https://youtu.be/nMVteEI2JuQ

**Comment by viciious** [comment] 2016-03-07 11:39
@hettoo

**Comment by viciious** [comment] 2016-03-07 11:44
Although I'm not sure whether it's a real issue or just nitpicking.

**Comment by hettoo** [comment] 2016-03-07 12:57
It does look like an issue to me, although nothing serious.
However, I can't reproduce this with qfusion... adem, can you check that you had all your modules compiled with the latest gs_pmove there?

For me it does sometimes give a jump sound instead of the walljump sound, but only when walljumping at a very low point (much lower than the former limit) and only while moving downwards.
I can't really see why this happens, though, but it should be rare in practice anyhow.

**Comment by adem4ik** [comment] 2016-03-07 13:03
I've used latest binaries/modules from private repo which gets synced with qfusion repo.
P.S. My nick name is **adem**, not adam

**Comment by hettoo** [comment] 2016-03-07 13:37
Ok, mine is **hettoo**, not [hetto](https://www.warsow.gg/forum/thread/t/231650#post-231650). :D

In the meantime I think I can explain the anomaly I observed with the jump: it is possible that in the same frame first a jump is detected in PM_CheckJump, which then sets pm->groundentity to -1, and thus because we are now officially in the air, PM_CheckWallJump, which is executed afterwards, may still decide that there is a walljump. The jump is already registered, and I guess it suppresses the walljump sound effect (this last part is the actual issue: the walljump sound should overrule the jump sound like it would if it were a frame later; but I don't know the specifics of that code).

One might expect that the same thing could happen with a dash instead of a jump, as the dash is also checked before the walljump.
However, it is checked after the jump, and since for a low walljump jump needs to be pressed, if the dash happens in the same frame as the walljump, we must be at the ground and so there must also be a jump in that frame, the sound of which should suppress the other two sounds.

**Comment by hettoo** [comment] 2016-03-13 18:21
I'll have to admit I don't fully understand what is going on here or how it might be fixed. As remarked earlier, this is nowhere near a critical issue, but at least to me it still nags a bit.

For additional reference, I found that in this run by ale there are two instances of walljumps where only the sound of a jump comes through:
https://www.youtube.com/watch?v=HdMdcQ2InmU
One is mid 0:06 and the other just before 0:17.

Actually, adem, I think your video also has jump sounds for those walljumps, and not dash sounds. Could that be? This would eliminate our discrepancy.
For bigvic these sounds are not easily distinguished. It was clearer when I tried with bobot.

**Comment by hettoo** [comment] 2016-03-13 22:05
It gets even more interesting because the above video was made on Warsow, without my walljump height patch...

Apparently, in this case the bug is only encountered during demo playback. Ale says he heard every single walljump sound while making the following demo, whereas when you play it two of the walljumps are not heard.
https://dl.dropboxusercontent.com/u/22044693/warsow/wjtest20.wdz20
(Edit: earlier demo was actually recorded with new modules, fixed now.)

**Comment by hettoo** [comment] 2016-03-14 15:52
Ok, I traced this to the sound module. It only happens with s_module 1, which allows only one sound per entity at the same time: https://github.com/Warsow/qfusion/blob/master/source/snd_qf/snd_dma.c#L218
I think it should be safe to just remove that block, right?

Note that in the described situation you will then hear the jump and walljump sounds at the same time, but that is how it should be.

**Comment by viciious** [comment] 2016-03-14 15:55
I don't think that playing two sounds simultaneously is how it should be.

**Comment by hettoo** [comment] 2016-03-14 16:42
This is because there is a jump and a walljump at the same time (as described in my third comment).
Note that the walljump is triggered last, but snd_qf processes them the wrong way around; snd_openal does get that right.

I liked the idea of not truncating sounds, but maybe you are right and it is better to just fix that order and get those modules consistent. To do so, change "sort->begin < ps->begin" to "sort->begin <= ps->begin" here: https://github.com/Warsow/qfusion/blob/master/source/snd_qf/snd_dma.c#L621

**Comment by viciious** [comment] 2016-03-14 17:05
So changing the sorting comparison will ensure FIFO order of playsounds, right?

**Comment by hettoo** [comment] 2016-03-14 17:07
Exactly.

**Closed as completed** 2016-03-14 18:25 UTC
